name: Test-Dev-Job
on:
  workflow_dispatch: 
    branches:
    - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update -y && test -d ~/.ssh || mkdir ~/.ssh && chmod 700 ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && chmod 600 ~/.ssh/config
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: git config --global user.email "vinod.gole@galaxyweblinks.in"
      - run: git config --global user.name "vinod.gole@galaxyweblinks.in"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: git ftp init --user ${{ secrets.USER }} --passwd ${{ secrets.PASSWD }} "sftp://3.88.221.180:~/html/" -f
